# Generated by Django 3.0.8 on 2020-07-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200717_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
