# Generated by Django 3.0.8 on 2020-07-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='age',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='univ',
        ),
    ]
